# Generated by Django 2.2.1 on 2019-09-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='cropped close-up-of-coffee-cup-on-table-312418.png', upload_to=''),
        ),
    ]
