# Generated by Django 2.2.4 on 2019-08-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Enter a description for this image.', max_length=35)),
                ('image', models.ImageField(upload_to='./pictures/')),
            ],
        ),
    ]
