# Generated by Django 2.2.1 on 2019-10-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
    ]
