# Generated by Django 2.2.1 on 2019-10-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local_image',
            field=models.CharField(default='', max_length=50),
        ),
    ]
