# Generated by Django 2.2.4 on 2019-08-19 22:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20190811_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pictures',
        ),
        migrations.AddField(
            model_name='product',
            name='delisted',
            field=models.BooleanField(default=False, help_text='Delisting an item marks it as no longer available.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the price of this product.', max_digits=7, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(99999.99)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.User'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
