# Generated by Django 2.2.1 on 2019-10-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_product_local_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='local_image',
            field=models.CharField(default='/images/product_image_01.jpg', max_length=50),
        ),
    ]
