# Generated by Django 2.2.1 on 2019-10-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20191005_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='local_image',
            field=models.CharField(max_length=50),
        ),
    ]
