# Generated by Django 2.2.1 on 2019-10-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20191005_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='zip_code',
        ),
    ]
