# Generated by Django 2.2.1 on 2019-10-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20191005_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the total = price * quantity of this product.', max_digits=6),
        ),
        migrations.AddField(
            model_name='shoppingcartproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the total = price * quantity of this product.', max_digits=6),
        ),
    ]
