# Generated by Django 2.2.3 on 2019-08-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='payment',
            new_name='payment_method',
        ),
        migrations.AddField(
            model_name='user',
            name='order_buyer',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='order_seller',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
